const platforms = [
  { slug: 'win', name: 'PC' },
  { slug: 'ps', name: 'Playstaion' },
  { slug: 'ps2', name: 'Playstation 2' },
  { slug: 'ps3', name: 'Playstation 3' },
  { slug: 'ps4--1', name: 'Playstation 4' },
  { slug: 'playstation-5', name: 'Playstation 5' },
  { slug: 'psp', name: 'PSP' },
  { slug: 'psvita', name: 'PS Vita' },
  { slug: 'xbox', name: 'Xbox' },
  { slug: 'xbox360', name: 'Xbox 360' },
  { slug: 'xboxone', name: 'Xbox One' },
  { slug: 'xbox-series-x', name: 'Xbox Series X' },
  { slug: 'nes', name: 'NES' },
  { slug: 'snes--1', name: 'SNES' },
  { slug: 'n64', name: 'Nintendo 64' },
  { slug: 'ngc', name: 'Nintendo GameCube' },
  { slug: 'wii', name: 'Wii' },
  { slug: 'wiiu', name: 'Wii U' },
  { slug: 'switch', name: 'Switch' },
  { slug: 'gb', name: 'Game Boy' },
  { slug: 'gbc', name: 'Game Boy Color' },
  { slug: 'gba', name: 'Game Boy Advance' },
  { slug: 'nds', name: 'Nintendo DS' },
  { slug: '3ds', name: 'Nintendo 3DS' },
  { slug: 'smd', name: 'MegaDrive/ Sega Genesis' },
  { slug: 'saturn', name: 'Sega Saturn' },
  { slug: 'dc', name: 'Dreamcast' },
  { slug: 'neo-geo-pocket', name: 'NeoGeo Pocket' },
  { slug: 'neo-geo-pocket-color', name: 'NeoGeo Pocket Color' },
  { slug: 'ios', name: 'iOs' },
  { slug: 'arcade', name: 'Arcade' },
  { slug: 'android', name: 'Android' },
  { slug: 'linux', name: 'Linux' },
]

export default platforms
